### PR TITLE
Refactor back end code, improve emails

### PR DESCRIPTION
**Pull request by ceddlyburge**
Delete the Azure Function. This isn't required and as I understand it is a safeguard against leaving open (unauthenticated) routes. I have refactored the back end server code so that it would now be difficult to leave open routes by mistake.

Improve the email format. The emails now try and mimic the look and feel of the website. Outlook has terrible support for html emails, so it is not exact, and the styles / html is quite different. This is a shame, but unavoidable.

Refactor back end code:

- Separate each endpoint in to its own file
- Separate (nearly) each part of the express app setup in to its own file
- Reduce nesting (and keep intellisense) by require ing constants
-  Move authenticate to middleware, to make routes simpler and make it harder to add an unathenticated route by mistake.
- Remove unused endpoints

This PR has already been merged with Clement's repo

### CODE REVIEW

**Comment by Alan-Hinton** [comment]
As discussed it would be good to make two npm build actions, one to build the Tec version and one to build the SMART version.  These would then pick the appropriate projects.json file.  That way we can have both projects.json files in github.
It might also be worth having multiple start commands for the same reason.  See https://github.com/resgroup/smart-ui/blob/master/package.json for an example of how we have done this for SMART-UI

**Comment by ceddlyburge** [comment]
Hi Alan

I have had a think about this, and I don’t think it makes sense, being as this is an open source project and potentially used by other people. This PR for example is already merged in to Clems original repo, and it wouldn’t make sense to have smart and tec specific stuff in there.

I think it might make more sense just to .gitignore this file.

Unless you have any other ideas.

Essentially we want to commit it to our own repos, but not include it when commiting to external repos.

Cheers

Cedd Burge
Software Developer Lead

D +44 1923 299 497
cedd.burge@res-group.com<mailto:cedd.burge@res-group.com>  |  www.res-group.com<http://www.res-group.com/>

[cid:image001.gif@01D3DE4E.0AEDD350]<http://www.res-group.com/>     [cid:image002.gif@01D3DE4E.0AEDD350] <https://www.linkedin.com/company/res-group>   [cid:image003.gif@01D3DE4E.0AEDD350] <https://twitter.com/RESGroup>   [cid:image004.gif@01D3DE4E.0AEDD350] <https://www.youtube.com/c/RESGroupVideo>

Home Safe - Every Day

Renewable Energy Systems Limited, registered in England and Wales with Company Number 1589961
Registered Office: Beaufort Court, Egg Farm Lane, Kings Langley, Hertfordshire WD4 8LR

**Comment by ceddlyburge** [comment]
Hi Alan, I have added projects.json to gitignore. You may still have to merge it this time, and then fix it up afterwards, but it should be ok from here on in. 

I've added an issue to remove the reliance on projects.json, and use repo topics instead.

**Comment by ceddlyburge** [comment]
Hi Alan, I have added projects.json to gitignore. You may still have to merge it this time, and then fix it up afterwards, but it should be ok from here on in. 

I've added an issue to remove the reliance on projects.json, and use repo topics instead.

**Comment by Alan-Hinton** [comment]
I think you need to explicitly remove the projects.json from the repo using `git rm` (see https://gist.github.com/tsrivishnu/a2f3adbbca9fcad5f3597af301ad1abb ).  It might also be worth adding a projects.json.sample so we have a clue about the format in the repo.

**Comment by ceddlyburge** [comment]
Hi Alan, I’ve pushed a couple of commits for this.

Cheers

Cedd Burge
Software Developer Lead

D +44 1923 299 497
cedd.burge@res-group.com<mailto:cedd.burge@res-group.com>  |  www.res-group.com<http://www.res-group.com/>

[cid:image001.gif@01D3E6BF.BE2B09F0]<http://www.res-group.com/>     [cid:image002.gif@01D3E6BF.BE2B09F0] <https://www.linkedin.com/company/res-group>   [cid:image003.gif@01D3E6BF.BE2B09F0] <https://twitter.com/RESGroup>   [cid:image004.gif@01D3E6BF.BE2B09F0] <https://www.youtube.com/c/RESGroupVideo>

Home Safe - Every Day

Renewable Energy Systems Limited, registered in England and Wales with Company Number 1589961
Registered Office: Beaufort Court, Egg Farm Lane, Kings Langley, Hertfordshire WD4 8LR

**Pull request merged**
